runtime: nodejs16

instance_class: F2

# threadsafe : true

env_variables: 
  BUCKET_NAME: "ng-app-bucket457"

handlers:
- url: /
  static_files: dist/shop/index.html
  upload: dist/*

- url: /
  static_dir: dist/shop

